# Generated by Django 4.2.3 on 2023-09-25 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_customuser_referral_code_customuser_referred_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="referral_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="referred_by",
        ),
    ]
